### ISSUE TITLE
xenial image not including fastcgi?

### ISSUE THREAD

**Issue by IAmJulianAcosta** [openresty/docker-openresty#11]
I downloaded xenial image but I'm getting errors with all fastcgi directives:

```
nginx                  | nginx: [emerg] unknown directive "fastcgi_read_timeout" in /usr/local/openresty/nginx/conf/nginx.conf:39
```

Using the same `nginx.conf` with official nginx image is ok

**Comment by neomantra** [comment]
This is by design. See #6.  Also see "Build Options" in the README on how to enable it in your own build.  

Are you actually using OpenResty/ngx.lua with CGI scripts?  Or would an nginx only image work for you?

Perhaps we should make an Ubuntu-full image?

**Comment by IAmJulianAcosta** [comment]
+1 to full image, would be very useful for people like me that are new to this

**Comment by IAmJulianAcosta** [comment]
@neomantra I tried with the option `--with-http_fastcgi_module`, but with no luck: `--without-http_scgi_module`

**Comment by agentzh** [comment]
I think we should include fastcgi and uwsgi modules by default since many people use OpenResty as a dynamic web gateway instead of a self-contained app server. Such hybrid setup is actually a typical use case :)

Eventually I hope the docker image can use the official OpenResty binary packages so that it's easier to sync:

http://openresty.org/en/linux-packages.html

But we only have rpm packages right now. Still waiting for .deb ones from the community :)

**Comment by neomantra** [comment]
Ok it is easy enough to add them back in.  Will do that soon.

**Comment by neomantra** [comment]
@agentzh   Once the RPM packaging has stabilized, let me know and I'll adapt the Centos image.

**Comment by agentzh** [comment]
@neomantra The RPM packages are production ready now.
