### ISSUE TITLE
should this image contains lua-resty-http?

### ISSUE THREAD

**Issue by BrickXu** [openresty/docker-openresty#13]
Hi all,

Our team use openresty with lua-resty-http in the production, and we want to migrate some nginx server from vm to container via this image, but some of useful libraries could not found in it. 

Is there any roadmap to support 3rd library in this image?

Thx

**Comment by neomantra** [comment]
Hello, I actually use `lua-resty-http` myself with this image.  But, since there are a myriad of third party libraries, I'm hesitant to put my favorite libraries (or yours) there unless they are extremely common (i.e. would possibly be included with OpenResty itself).

All of the images, except `alpine`, support LuaRocks out of the box, as described (in the README)[https://github.com/openresty/docker-openresty#luarocks].

Each service I make has its own Dockerfile which sets up its environment and content.  Here's what one of mine looks like:

```
FROM openresty/openresty:xenial
MAINTAINER Evan Wies <evan@somewhere.com>

RUN /usr/local/openresty/luajit/bin/luarocks install lua-resty-http 

COPY nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
COPY service.lua /usr/local/openresty/nginx/resty/service.lua
```

If most of your services use a common set of libraries, then you can build an intermediate image with all those libraries, then base your service-specific images `FROM` that one.

Let me know if this approach doesn't work for you.

**Comment by BrickXu** [comment]
@neomantra  thanks for your response, very very nice example for me!
