### ISSUE TITLE
怎么设置时区

### ISSUE THREAD

**Issue by 362228416** [openresty/docker-openresty#16]
怎么设置时区？

**Comment by neomantra** [comment]
Hello, I do not speak that language, but the Cloud has given me the super powers to understand you.   However, I must respond in English.

I think that is a general Docker question, rather than an OpenResty question.  If I misunderstood and something else is broken, please let me know.

You can bake the timezone into a derived image using the following Dockerfile for your build flavor.  

 * Alpine
```
FROM openresty/openresty:alpine
RUN apk add --no-cache tzdata \
    && cp /usr/share/zoneinfo/America/New_York /etc/localtime \
    && apk del tzdata
```
 * Xenial
```
FROM openresty/openresty:xenial
# Ubuntu 16.04 tzdata bug:
#   https://bugs.launchpad.net/ubuntu/+source/tzdata/+bug/1554806
RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime \
    && dpkg-reconfigure -f noninteractive tzdata
```

You can also execute these `RUN` commands in a running container with `docker exec`.

**Comment by 362228416** [comment]
@neomantra Thanks, it's ok.
