### ISSUE TITLE
No el7 option on docker hub

### ISSUE THREAD

**Issue by 9point6** [openresty/docker-openresty#173]
Hey, 

[CentOS 8 is end-of-life this year, whereas CentOS 7 is end-of-life in 2024](https://wiki.centos.org/About/Product). For this reason we (and I suspect many others) will not be upgrading to it in production, so would like to continue using CentOS7 for running our tests. 

I've noticed that you have upgraded your `centos` and `centos-rpm` tags on docker hub to use EL8 as a default now, which is fair enough as many would probably expect the latest release as the base. 

However, Is there any scope to maintain a centos7 branch for the people who intend to remain on the longer supported version?

Thanks for all your work on this project!

**Comment by neomantra** [comment]
Hi, I didn't realize CentOS 7 was more LTS than 8.. and [upstream supports CentOS 7](http://openresty.org/en/linux-packages.html), looks like it supports more architectures on it.

Given that, it makes sense to have a `centos7` flavor and `centos7-rpm` flavor co-exist with the others... it might even be able to be expressed as build flags in the CI rather than extra Dockerfiles.  Or suggest some other naming convention.

I don't have the time to do that but happy to take PRs.

**Comment by neomantra** [comment]
I merged @kshitijmjoshi  's CentOS 7 work...

I revamped the travis build and added multi-architecture build for Centos7 since upstream has both `x86_64` and `aarch64` packages...

This is all on `master` now... 

Can anybody interested in this please test it some and report back?   Then I'll tag it as `1.19.3.1-4`.

Relevant image is:  `openresty/openresty:centos7`

**Comment by 9point6** [comment]
I tried this out today and it seems good to me!
