### ISSUE TITLE
alpine and luarocks

### ISSUE THREAD

**Issue by jney** [openresty/docker-openresty#23]
i wish you had 2 versions of alpine linux, one including luarocks.

**Comment by neomantra** [comment]
I’m going to make an `alpine-opm` image that has OPM installed.  It is not
installed by default because it doubles the image size.  I will include
luarocks in that image too.


On November 26, 2016 at 7:51:11 AM, Jean-Sébastien Ney (
notifications@github.com) wrote:

i wish you had 2 versions of alpine linux, one including luarocks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/openresty/docker-openresty/issues/23>, or mute the
thread

**Comment by neomantra** [comment]
I added an image named `alpine-fat` that keeps a build system intact, keeps perl (needed by `opm`)  and installs luarocks to `/usr/local/openresty/luajit/bin/luarocks`

If you have issues, feel free to reopen this or make a new issues.

**Comment by bobelev** [comment]
When I run `/usr/local/openresty/luajit/bin/luarocks install lua-cjson` in `alpine-fat` container i get this error:
```
Warning: Failed searching manifest: Failed fetching manifest for https://luarocks.org - Failed downloading https://luarocks.org/manifest - /root/.cache/luarocks/https___luarocks.org/manifest
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/ - Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/manifest - /root/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moonrocks-mirror_master_/manifest
Warning: Failed searching manifest: Failed fetching manifest for http://luafr.org/moonrocks/ - Failed downloading http://luafr.org/moonrocks/manifest - /root/.cache/luarocks/http___luafr.org_moonrocks_/manifest
Warning: Failed searching manifest: Failed fetching manifest for http://luarocks.logiceditor.com/rocks - Failed downloading http://luarocks.logiceditor.com/rocks/manifest - /root/.cache/luarocks/http___luarocks.logiceditor.com_rocks/manifest
```

**Comment by bobelev** [comment]
Turns out that luarocks needs `unzip` and `curl` packages. Please add them to `alpine-fat` image, so we can have working `luarocks` by default.

**Comment by neomantra** [comment]
Thanks for reporting, it will be on the alpine-fat tag soon (once Docker Hub is done building it).
