### ISSUE TITLE
docker compose fails to run bullseye/Dockerfile with RESTY_DEB_FLAVOR=-debug

### ISSUE THREAD

**Issue by renatosc** [openresty/docker-openresty#259]
Docker compose fails to run bullseye/Dockerfile with RESTY_DEB_FLAVOR=-debug.

I get the following error:
`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/bin/openresty": stat /usr/bin/openresty: no such file or directory: unknown`

**Comment by neomantra** [comment]
Thanks for reporting this.  As noted, PR #260 was rejected due to security concerns, particularly for debug support.

Also noting you here you added:
>The current path /usr/bin/openresty does not exist. The correct one would be /usr/bin/openresty-debug (or in more generic way, "usr/bin/openresty{RESTY_DEBUG_FLAVOR}". Would you be okay with a change to that generic way then? (I think tried that first but it was not liking the string concatenation, I can try again.

Anything involving injecting `RESTY_DEB_FLAVOR` into `CMD` won't work either (unsupported by `Dockerfile` for various and similar reasons).

As a workaround, you can you try running like this?
```
docker run --entrypoint=/bin/bash bullseye-debug-aarch64 -c "openresty -g 'daemon off;'"
```

One solution  is to have a specific `Dockerfile.debug` Dockerfile and `Dockerfile.valgrind` that put hard-code the correct paths at the end.  I don't think I'd like to maintain a whole ton (since there is a workaround, but certainly it's convenient to pull a debug image. Right now one has to build their own.   I think this is what I'm going to do -- thoughts on that?

**Comment by neomantra** [comment]
This is a simpler version of that command.  These images do not set an ENTRYPOINT, so it inherits the parent OS images' ENTRYPOINT which are bash-ish:

```
# bullseye-debug-aarch64 is the debug image built
docker run bullseye-debug-aarch64 /usr/bin/openresty-debug -g 'daemon off;'
```

**Comment by neomantra** [comment]
I added this and you can try to build this [Dockerfile.debug](https://github.com/openresty/docker-openresty/blob/b1.25.3/bullseye/Dockerfile.debug).  I'm still working out some CI issues.

**Comment by neomantra** [comment]
This should work for you now:
```
docker run -it --rm openresty/openresty:1.25.3.2-1-bullseye-debug
```

If it doesn't work or there's further issues related to this, feel free to re-open.  Thanks!
