### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by rpatelob** [openresty/docker-openresty#41]
Could someone please post a simple hello world?

**Comment by neomantra** [comment]
Taking you literally:
```
docker run  --entrypoint=/usr/local/openresty/bin/resty openresty/openresty:xenial -e  'print "hello world"'
```
Be more specific of what you are looking for and we can try to help.

**Comment by rpatelob** [comment]
Actually I want to dockerise my openresty application. I posted a question on stackoverflow, I am a newbie to docker so couldn't able to start a simple hello world application like [this](https://openresty.org/en/getting-started.html). This is my [question](https://stackoverflow.com/questions/44589081/openresty-hello-world-with-docker). You will find a detailed over there.

**Comment by rpatelob** [comment]
`docker run -it -p 8888:80 -v /home/software/docker/openresty:/usr/local/openresty/nginx/html:ro openresty/openresty:1.11.2.3-xenial` using this CLI it's showing my custom HTML then I tried to link custom nginx.conf using below CLI and it's not working.
`docker run -it -p 8888:80 -v /home/software/docker/openresty:/usr/local/openresty/nginx/html:ro -v /home/software/docker/openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro openresty/openresty:1.11.2.3-xenial
`
Any idea what I missed?

**Comment by neomantra** [comment]
There are some problems in your SO posting, which maybe are just copy-paste errors into SO.   Notably, you build `user/openresty` but run `rahul/openresty`.   Also, the CMD line in your `Dockerfile` is probably not doing what you expect.

But I took your files..... in your `nginx.conf`, I commented out `daemon off;` (the ENTRYPOINT in 
 the Dockerfile takes care of that).  Then I ran it like this, keeping your app in its own directory:
```
cd <dir-with-files>
mkdir logs
docker run -it -p 8080:8080 -v $(pwd):/app openresty/openresty:1.11.2.3-xenial -p /app -c nginx.conf
```

Note I didn't run it with `:ro` (read-only volume) because as configured it writes to files in that directory.

You are right that a simple use case is not well documented.  I'm gonna revamp the packaging because of the new Debian packaging. I will seek to make simple application use cases simpler and clearer, along with improved documentation.    I'll be doing this in July timeframe.

**Comment by rpatelob** [comment]
Thanks @neomantra , your CLI is working, except I haven't understood it correctly.
Would you mind to explain it a bit?

**Comment by neomantra** [comment]
I'll break it down:
`docker run -it -p 8080:8080 -v $(pwd):/app openresty/openresty:1.11.2.3-xenial -p /app -c nginx.conf`

 * `docker run -it` [runs a docker container](https://docs.docker.com/engine/reference/commandline/run)  in interactive mode.  You could pass `-d` instead of `-it` to daemonize it.

 * `-p 8080:8080` publishes the container's port `8080` to the host's port `8080`

 * `-v $(pwd):/app` mounts a mount volume in the container, mapping the host's current working director (`$(pwd)`) to `/app` in the container.

 * `openresty/openresty:1.11.2.3-xenial` is the name of the image to run.  After this, the rest of the arguments are to `nginx`, not docker.

 * `-p /app` sets the nginx prefix directory to `/app`

 * `-c nginx.conf` sets the nginx conf file to `nginx.conf`, actually using `/app/nginx.conf` because of the prefix.
