### ISSUE TITLE
Use CMD instead of ENTRYPOINT

### ISSUE THREAD

**Issue by elefthei** [openresty/docker-openresty#52]
In docker ENTRYPOINT is making it harder to debug by overwriting the entrypoint, 
chaining containers together, makes it easier to inherit from this container in other Lua containers.
It's easier to run for example:
```
docker run -it openresty/openresty sh
```

**Comment by elefthei** [comment]
https://github.com/openresty/docker-openresty/pull/51

**Comment by neomantra** [comment]
I am going to accept this change, notably because it is also how the nginx image works.

But, as it could be breaking to some people, I'm not going to put it on the 1.11.2.5 tag. 

Although you did a search/replace for `ENTRYPOINT` in the README, I think that:
1. The changelog shouldn't be modified
2. The README samples (e.g. using the `resty` CLI util) should be modified to not use `--entrypoint`

Can you update that?

I'm going to have sporadic internet over the next week, but will attend to this more fully after Labor Day.

**Comment by elefthei** [comment]
Reverted on changelog, fixed the README.md to apply to CMD. Thanks!

**Comment by neomantra** [comment]
I figured out how to fix the attribution.
