### ISSUE TITLE
resty util requires perl

### ISSUE THREAD

**Issue by neomantra** [openresty/docker-openresty#6]
We were discussing thinning out the Alpine module in #5.

The `resty` utility script is written in perl.   The perl dependency is 40M, almost doubling the size of the image.

Do we exclude perl from the alpine images and require another image on top of it to get resty working?

**Comment by neomantra** [comment]
@ruslantalpa this reminds me of another reason why I included the perl module -- because i had to include the perl infrastructure anyway.

**Comment by ruslantalpa** [comment]
Yes, removing perl breaks resty utility, and it's also broken in ficusio/openresty
I'm not sure what to say/do exactly, on one hand, if you use this for production you want it small and don't need resty. While in develompment you might need resty (although i rarely used it)

**Comment by neomantra** [comment]
Something I like about the ficusio/openresty images is that he openly keeps Alpine light and Debian bloated.

So I think what I'm going to do is remove perl (and wsci and scgi support) from the Alpine images and bloat up the Ubuntu ones with some more dev tools (as suggested in #1).

**Comment by ruslantalpa** [comment]
I partially agree with your decision but not entirely. Here is where i am coming from.

To me, the reason ppl using openresty, do that for lua, and there is a very small chance they will be using any cgi/fastcgi (read php) with this image, so cgi can be removed from both images.

When you say "keep alpine light" i agree as long as we are talking about things you would use in command line, dev tools. If you are taking about features compiled in nginx, i would strive to keep tehm as close as possible. If that can be accomplished, then ppl using these images, while in "exploratory/testing" mode they can base their work on debian image (to be able to jump into the container, test things with resty ... stuff like that) and when they go into production, they just switch to the alpine image and everything works the same (since both nginx binaries have the same features).

PS: in a issue of ficusio/openresty repo i mentioned this reppo and asked them to join this effort. It might be a good idea to add a gitter room for this repository so that ppl can chat/exchange ideas without filling the repo with issues that are basically chats

**Comment by neomantra** [comment]
Yes great comments.   As I thought about it more, I was thinking of removing it from both (because if they wanted CGI they could just use the nginx image).

I saw your note on that repo (which I hadn't seen before) and do hope there is some cross-polination.  There is an OpenResty gitter.  I'll add a reference to that to the README.   I'd rather it all go on there rather than some micro-channel just for the docker tooling.

**Comment by neomantra** [comment]
This was completed with f20053d05da052376e0329df30fdb1bb210d9453.   

Alpine no longer has the `perl` package.  All the variants have http_perl_module, FastCFI, uWSGI, and SCGI remove.
