### ISSUE TITLE
Old lua-cjson bundled in openresty:xenial docker image

### ISSUE THREAD

**Issue by emvev** [openresty/docker-openresty#73]
Old version of lua-cjson is installed in /usr/local/openresty/lualib/cjson.so of the openresty/openresty:xenial image.
The default lua_package_path contains /usr/local/openresty/lualib before 
/usr/local/openresty/luajit/lib/lua/5.1/ where lua-cjson luarock is installed.
The version in lualib does not contain https://github.com/openresty/lua-cjson/commit/b5e364c7c60167995944ed3a3b9c54d9a377fc1d

**Comment by neomantra** [comment]
@emvev So it seems like there are two things here?

1) You are saying that the bundled OpenResty cjson is old.  But this test seems to indicate that it is the version you point to?   
```
# I used a specific image tag -- same result for the latest xenial tag
$  docker run -it --rm openresty/openresty:1.13.6.2-0-xenial /usr/local/openresty/bin/resty -e 'cj = require "cjson" ; print(cj._VERSION)'
2.1.0.6
```
Is something else going on?

---

2) You are saying that the `lua_package_path` in the `nginx.conf` prevents the loading of your installed rock and we can see that path (showing `_cpath` because we are talking about `.so` files) with this:
```
$ docker run -it --rm openresty/openresty:1.13.6.2-0-xenial /usr/local/openresty/bin/resty -e 'print(package.cpath)'
/usr/local/openresty/site/lualib/?.so;/usr/local/openresty/lualib/?.so;./?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/openresty/luajit/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so
```
That cpath is the default upstream OpenResty `lua_package_cpath`.  Presumably that is to get maximal compatibility?   The Docker images do not modify this.   

If this is an issue, like in your case of overriding an included package, you can replace the included [`nginx.conf`](https://github.com/openresty/docker-openresty/blob/master/nginx.conf) and set the `lua_package_cpath` in the `http` section.   You can replace that in various ways (copying into container, making your own derived image and `COPY`ing it in, bind-mounting, etc.)

---

Separately, I was planning on eventually removing LuaRocks from the built images and only including a sample `Dockerfile.xenial-luarocks` and documentation.  Per this [OpenResty web page](http://openresty.org/en/using-luarocks.html), LuaRocks in OpenResty is deprecated.

**Comment by emvev** [comment]
You are right. With tag 1.13.6.2-0-xenial the version is OK.

`$ docker run -it --rm openresty/openresty:1.13.6.2-0-xenial /usr/local/openresty/bin/resty -e 'cj = require "cjson" ; print(cj._VERSION)'`
`2.1.0.6`

But I was referring to tag :xenial which I'm using, because I thought that it is the latest xenial version. When running the same command on :xenial:
`$ docker run -it --rm openresty/openresty:xenial /usr/local/openresty/bin/resty -e 'cj = require "cjson" ; print(cj._VERSION)'`
`2.1devel`

My image IDs for reference:
- openresty/openresty                   1.13.6.2-0-xenial   f1f40db88145
- openresty/openresty                   xenial              36b32fe5a26b

**Comment by neomantra** [comment]
Your local image may be stale.   [Unfortunately Docker Hub doesn't show image ID.]  

Try pulling:
`docker pull openresty/openresty:xenial`

I'm seeing this image ID and the following result:
```
$ docker pull openresty/openresty:xenial
xenial: Pulling from openresty/openresty
Digest: sha256:83d2d29c264f228c65def1fcb38d3025dcf17c75ce4bc9b3286c8b3482752338
Status: Image is up to date for openresty/openresty:xenial
$ docker run -it --rm openresty/openresty:xenial /usr/local/openresty/bin/resty -e 'cj = require "cjson" ; print(cj._VERSION)'
2.1.0.6
```

Currently the only difference between `xenial` and ` 1.13.6.2-0-xenial` is a change to the AUTHORS file.

**Comment by emvev** [comment]
```
$ docker -v
Docker version 17.06.2-ce, build cec0b72
$ docker rmi openresty/openresty:xenial
Untagged: openresty/openresty:xenial
Untagged: openresty/openresty@sha256:4299151296ec59d28efaf2b359c4b146e0663ae76d9fbe7e0fa997d969f57f96
Deleted: sha256:36b32fe5a26b5e2eeab7b1d10bff155f99b7623927ea5d64377aa80024048f79
...
$ docker pull openresty/openresty:xenial
xenial: Pulling from openresty/openresty
660c48dd555d: Pull complete
...
50a3bdfa425d: Pull complete
Digest: sha256:4299151296ec59d28efaf2b359c4b146e0663ae76d9fbe7e0fa997d969f57f96
Status: Downloaded newer image for openresty/openresty:xenial
$ docker run -it --rm openresty/openresty:xenial /usr/local/openresty/bin/resty -e 'cj = require "cjson" ; print(cj._VERSION)'
2.1devel
```
After upgrading docker-ce to version 18.03 docker pulls the correct image.
```
$ docker pull openresty/openresty:xenial
xenial: Pulling from openresty/openresty
Digest: sha256:83d2d29c264f228c65def1fcb38d3025dcf17c75ce4bc9b3286c8b3482752338
Status: Image is up to date for openresty/openresty:xenial
$ docker run -it --rm openresty/openresty:xenial /usr/local/openresty/bin/resty -e 'cj = require "cjson" ; print(cj._VERSION)'
2.1.0.6
```
