### ISSUE TITLE
docker restart nginx    look

### ISSUE THREAD

**Issue by chenyongze** [openresty/docker-openresty#75]
Error response from daemon: driver failed programming external connectivity on endpoint nginx (d0bfd56dc4cf4550ec3733eca45307831cd31f477f8542946432905edb38cf52):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8689 -j DNAT --to-destination 192.168.0.2:80 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1))

**Comment by chenyongze** [comment]
centos 7.x

**Comment by neomantra** [comment]
I think this issue is unrelated to `docker-openresty` and probably with `iptables` or docker configuration.

Some Googling lead to this link:
https://success.docker.com/article/iptables-error-when-starting-container-with-docker-run

If you think it is related to `docker-openresty`, please include information on how you invoked it, which image you are using, etc.
