### ISSUE TITLE
Any recommendations how to add custom modules to Dockerfile?

### ISSUE THREAD

**Issue by kireevco** [openresty/docker-openresty#79]
Hello, I'm trying to figure out what would be the best way to add images with custom modules like pagespeed or rtmp enabled to the openresty/openresty? (https://github.com/kireevco/docker-openresty/blob/master/alpine/Dockerfile-pagespeed)

I would like to start a discussion if that would be be even useful?
And if yes, any thought on how to integrate it with current CI (maybe a dimention similar to `alpine`, `alpine-fat`)?

Thanks!

**Comment by neomantra** [comment]
I think supporting a plethora of custom modules within this repo would be cumbersome.  We've converged on including whatever upstream non-container OpenResty has -- indeed many of the images now use OpenResty distro packaging instead of manual builds.  

We do provide mechanisms for modifying the build (e.g.with `RESTY_CONFIG_OPTIONS` and `RESTY_CONFIG_OPTIONS_MORE`).  Also dynamic modules can be built in a Dockerfile.  

For what you are doing, maybe we need to add a `build-arg` that lets you inject scripts commands?   
Or perhaps better, we could `ADD` a script and execute that in the build.  Then a dev could put their own script instead of the default (empty) one.  Then at least there's only a single file you have to manage, rather than weaving into these Dockerfiles.   Thoughts on that?

---

Separately, I definitely do not want automated builds of a variety of custom modules from this repo (meaning the official OpenResty organization repo).  We are not able to do the quality control needed for that.  That said, all of the CI tooling is open source, uses free services, and setting it up on your own repo is easy.

That said, I don't want to impede people like you who want to share their work.   Some ideas:

 * Have a `contrib` directory that is unsupported where contributed Dockerfiles can live.  There would not be an automated build though. (Or with that `ADD script` idea, include those.)

 * Have a file, either in repo or on a GitHub Wiki page, that links to specific forks or repos like yours, so people who are interested can utilize them.

**Comment by kireevco** [comment]
Thank you so much for such a vast response. I see where you are coming from.
* I like the idea of injecting a script, looks clean and won't pollute the main org repo.
* Contrib directory for Dockerfiles would also make sense. Or maybe only 'extra' scripts could live there, where I can use official Dockerfile and pass script name and `RESTY_CONFIG_OPTIONS`.
* I've seen someone doing a build matrix (see [tmaier/docker-compose](https://github.com/tmaier/docker-compose) which is an interesting approach for enabling automatic builds and testing multiple configs)

I will think a little bit more on this topic, as now I have really good input. 
Thanks again!

**Comment by RVN-BR** [comment]
Hi all, I'm interested in this too... I'd like to continue closely based to supported images, but need to inject a custom module which requires cloning and adding the module so I'd vote for adding a script cmd... Is this something that would be in "serious" or "semi-serious" consideration?  (mostly curious)... for now I'm going to have to copy the dockerfile I guess...

injecting a script to download and using RESTY_CONFIG_OPTIONS_MORE to add the module would free us up for pretty much anything I assume? plus it would be possible to include these args in a custom dockerfile using the image...

I'll keep following this issue! thks!!

**Comment by neomantra** [comment]
I don’t have the bandwidth right now to do this, but I would can and merge pull requests that implement it.

**Comment by RVN-BR** [comment]
Sounds good... I'll try to contribute something along the lines of what I spoke above...

any suggestions? some options I thought about...

adding any/all of these variables:
- a "temporary packages" - packages to add to the .build-deps apk add (which would automatically be removed after)...
- a permanent packages - self explanatory
- script snippet to run before configure
- script snippet after make

any other ideas?

**Comment by RVN-BR** [comment]
I apologize as I have only added the changes to the alpine version... if others need it I can whip up quickly...

**Comment by neomantra** [comment]
Thanks this pull request.  No worries on doing it just for alpine.  After review and maybe other comments, we can then expand it to the other built flavors.

**Comment by RVN-BR** [comment]
Hi @neomantra I have complemented my PR with a few more commits involving Documentation, a note on contributors, as well as the tentative contributions to Xenial and Bionic.  

Just a couple of notes FYI...
- I was unable to test Xenial and Bionic, but have been using Alpine image successfully. (Sorry, I didnt want this to linger open for too long but have been very busy with work)...
- In following with the way Xenial and Bionic images work, I didnt remove any of the Build dependency packages after install like happens on Alpine.  (I made a note on this in the readme).  I thought about implementing this, but since none of the other packages are removed, I thought it was better to leave?

Let me know if anything else needs tweaking 👍

**Comment by neomantra** [comment]
This is work now on `master` . People who are interested in this, please use it and leave feedback here.  I'll keep the issue open.  Thanks @RVN-BR for the changes.

**Comment by RVN-BR** [comment]
Great, will revert to official image again 👍

**Comment by RVN-BR** [comment]
Hi @neomantra  Dockerhub hasnt been updated yet, any idea what the schedule is on that? thanks!!

**Comment by neomantra** [comment]
Hi, the Travis CI built and tagged a bunch of 1.13.6.2-2 images:

https://hub.docker.com/r/openresty/openresty/tags/
https://travis-ci.org/openresty/docker-openresty/builds/453672040

Oh or do you mean the README page on Docker hub?  maybe i need to manyally update that.

**Comment by neomantra** [comment]
... and I just updated the main page on Docker Hub, thanks.

**Comment by RVN-BR** [comment]
Cool, I thought the readme was automatic so I didnt even check the images themselves... Will do later today!

thanks!
