### ISSUE TITLE
The :latest tag is out of date

### ISSUE THREAD

**Issue by Sertion** [openresty/docker-openresty#89]
When running `docker run openresty/openresty` you get a very old version of Openresty (based on Alpine 3.4.4, openresty 1.11.2.2) where the documentation provided in the readme is inapplicable.

Tagging a newer version of openresty/openresty with the latest tag would solve this issue.

**Comment by neomantra** [comment]
Thanks for pointing that out.   I will delete the tag `openresty/openresty` from the repo because it is too ambiguous.  While it is convenient to have an undecorated tag, I'm not sure which it should be. I'd personally prefer `-bionic` but I'm sure many would want `-alpine`, so I'll just force people to be explicit, as the current documentation suggests.

**Comment by neomantra** [comment]
Except that's apparently impossible to do....  so I'm tagging it with the latest `stretch-fat` which is built from upstream OpenResty packages, includes `opm`, is Debian-based, and is only 59MB.

 I've just done the re-tag of latest, but am leaving this open because I need to update TravisCI tooling for this going forward and the documentation.
