### ISSUE TITLE
alpine-fat: luarocks: failed producing checksum

### ISSUE THREAD

**Issue by akornatskyy** [openresty/docker-openresty#98]
## Steps to Reproduce

```sh
docker run -it --rm openresty/openresty:alpine-fat luarocks install lbase64
```

Error:
```
Installing https://luarocks.org/lbase64-20120820-1.src.rock

Do not use 'module' as a build type. Use 'builtin' instead.
gcc -O2 -fPIC -I/usr/local/openresty/luajit/include/luajit-2.1 -c lbase64.c -o lbase64.o
gcc -shared -o base64.so lbase64.o

Error: Failed producing checksum: No MD5 checking tool available -- please install 'md5', 'md5sum' or 'openssl' in your system
```

Note:
```sh
$ which md5sum
/usr/bin/md5sum
```

**Comment by neomantra** [comment]
If you run it in verbose mode, you'll see what's going wrong:
```
docker run -it --rm openresty/openresty:alpine-fat luarocks --verbose install lbase64

...
os.execute:     cd '/tmp/luarocks_lbase64-20120820-1-MhMFKe' && md5sum '--version'
md5sum: unrecognized option: version                    
BusyBox v1.28.4 (2018-12-31 18:05:13 UTC) multi-call binary.

Usage: md5sum [-c[sw]] [FILE]...

Print or check MD5 checksums

        -c      Check sums against list in FILEs
        -s      Don't output anything, status code shows success
        -w      Warn about improperly formatted checksum lines
Results: 3
  1 (nil): nil
  2 (string): exit
  3 (number): 1
...
```

The issue is that Alpine uses BusyBox's `md5sum` which doesn't support the `--version` flag that `luarocks` detection issue.

So this is really a "luarocks on alpine" issue not a docker-openresty issue...  I'll keep digging a bit for a work-around or something.

**Comment by akornatskyy** [comment]
Yes, makes sense. Here is a workaround:

```sh
apk add outils-md5
```

You might consider to add it to your image.

**Comment by neomantra** [comment]
Cool, thanks, I'm glad I sent that after my first dig, because I didn't realize the apk web GUI needed wildcards to find things.  So yes that works:

`docker run -it --rm openresty/openresty:alpine-fat /bin/sh -c 'apk add outils-md5 && luarocks install lbase64'`

I'll add it to the `alpine-fat` package list.
