### ISSUE TITLE
alpine3.9: segfault due to different openssl versions

### ISSUE THREAD

**Issue by akornatskyy** [openresty/docker-openresty#99]
The *nginx* process fails with *segfault* in case there is loaded dependency that uses alpine's openssl library (e.g. luaossl installed with luarocks).

Note, alpine 3.9 uses openssl version 1.1.1b-r1

### Workaround 1: Downgrade to alpine 3.8

Downgrade base image to alpine 3.8

```sh
docker build -t openresty/openresty:alpine --build-arg RESTY_IMAGE_TAG=3.8 .
```

### Workaround 2: Upgrade openssl sources to 1.1.1b

Upgrade openssl to match alpine's [version](https://pkgs.alpinelinux.org/packages?name=openssl-dev&branch=v3.9). 

```sh
docker build -t openresty/openresty:alpine --build-arg RESTY_OPENSSL_VERSION= "1.1.1b" .
```

### Workaround 3: use openssl-dev

Consider to use distro's [openssl-dev](https://pkgs.alpinelinux.org/packages?name=openssl-dev&branch=v3.9), that would significantly reduce image build time.

**Comment by neomantra** [comment]
Thanks for testing these and reporting workarounds for people searching on this.  There have been some OpenSSL mismatch issues on the `openresty` repo recently as well.   As the images are easy to customize, I hope users can find a solution that fits their needs.

re: Workaround 1:  I'd like to move to the latest release of Alpine for these images, but maybe we wait until Workaround 2 can happen.  
 **Have you successfully been using Alpine 3.8 and OpenResty 1.15 with the `luaossl` module?**
 
re: Workaround 2:  I haven't tried it myself, but there's multiple issues about it on the `openresty`'s GitHub.  Once OpenResty upstream officially supports OpenSSL 1.1.1, then the Docker images will be upgraded to use it.  Apparently that will be [soon after the OpenResty release](https://github.com/openresty/openresty/issues/456#issuecomment-492077147).  So this is ultimately the solution.

re: Workaround 3: OpenResty patches and builds its own OpenSSL, so we won't do this in the Docker images either.  From [here](http://openresty.org/en/rpm-packages.html): "We use our own builds of OpenSSL (through the openresty-openssl package), PCRE, zlib, and LuaJIT to ensure these critical components are up to date and well formed.")

### Workaround 4:

This is really what you need... to build `luaossl` against the OpenResty-installed OpenSSL.  The system OpenSSL shouldn't matter because these libraries really should [use the OpenResty-patched headers and libraries](https://github.com/openresty/openresty/issues/456#issuecomment-481931078).  

I started looking into this for you, as people had similar issues with `nginx` (wanting to build `luaossl` against its OpenSSL), but alas... the OpenResty Alpine build deletes all the source files so you can't really do this.

But maybe it is OK to use system ones as long as it is the same version (Workaround 1)?   I don't know what all the patches do, but if they change data structures, that could be bad.

**Comment by akornatskyy** [comment]
With respect to your reply, see my comments inline below, please.

> As the images are easy to customize, I hope users can find a solution that fits their needs.

That means I have to clone this repo and pass `--build-arg` parameter... it takes really long to build this image. Thus I do not believe it is convenient. This is actually what I did.

> re: Workaround 1: I'd like to move to the latest release of Alpine for these images, but maybe we wait until Workaround 2 can happen.

I believe it is the most desirable solution (workaround 1) at the moment, relatively easy. Please note, that with 3.8 I can install with apk openssl and openssl-dev; and compile, however, in order to run I have to change symlinks to the version that used during nginx/openresty build.

I have tested this path and it works (does not crash).

> Have you successfully been using Alpine 3.8 and OpenResty 1.15 with the luaossl module?

Yes, I issued the docker command as in Workaround #1 and was able to make it work as explained above. relatively painless path.

> re: Workaround 2: I haven't tried it myself, but there's multiple issues about it on the openresty's GitHub. Once OpenResty upstream officially supports OpenSSL 1.1.1, then the Docker images will be upgraded to use it.

It appears upgrade to `alpine 3.9` was prematurely.

> re: Workaround 3: OpenResty patches and builds its own OpenSSL, so we won't do this in the Docker images either. From here: "We use our own builds of OpenSSL (through the openresty-openssl package), PCRE, zlib, and LuaJIT to ensure these critical components are up to date and well formed.")

This implies you need to keep header files so others can use them as well... this is where you head to workaround 4.

You are blocked with workaround 2, it is not an option to use workaround 3, thus meantime workaround 1 would work.

> But maybe it is OK to use system ones as long as it is the same version (Workaround 1)? I don't know what all the patches do, but if they change data structures, that could be bad.

Yes, it works, just need to add symlinks (for libcrypto and libssl used during the build).

**Comment by neomantra** [comment]
Great, so if that's working then I will revert the alpine 3.9 change until OpenSSL 1.1.1 is available.

> It appears upgrade to alpine 3.9 was prematurely.

I did it in the RC phase so that any issues, such as this one, can be discovered and resolved before the main release.

**Comment by neomantra** [comment]
OK, this was reverted for in `1.15.8.1rc2-1`   I made issue #101 to address this later.   Thanks again for the report / testing.
